### ISSUE TITLE
SVGs fail to open in Illustrator CS5

### ISSUE THREAD

**Issue by brentajones** [Quartz/Chartbuilder#104]
Using the code as is (with the 1.0 SVG header), I get an error that says "The operation cannot complete because of an unknown error. [CANT]".

If I update the header to 1.1, the error is "This SVG is Invalid. Validate it before opening."

When validating, I get the error "there is no attribute "transform""

**Comment by cssExpert** [comment]
You guys need to remove the IDs from the file and it'll work wonders.

**Comment by pychap** [comment]
I removed ID, still got errors in both Illustrator and Photoshop.   
However, the file **_did open_** in Sketch. From Sketch I exported it as an EPS (I needed to place it on a Photoshop file) and all worked good!  
If you don't have Sketch you could [download it here](https://sketchapp.com/) and use it free for 30 days.  
Good luck!
