### ISSUE TITLE
Error in Internet Explorer

### ISSUE THREAD

**Issue by maartenzam** [Quartz/Chartbuilder#134]
I get the following error in my console in Internet Explorer 10 when accessing http://quartz.github.io/Chartbuilder/:

Unable to get property 'item' of undefined or null reference
gneisscharts.js, line 1092 character 4

I didn't check other IE versions, but Safari, Firefox and Chrome don't throw me this error.

**Comment by yanofsky** [comment]
Seeing how this is a bug for old CB i'm going to close it out.
