### ISSUE TITLE
Q for localization: At what lines are numbers formatted?

### ISSUE THREAD

**Issue by n-kb** [Quartz/Chartbuilder#138]
I'm trying to modify CB so that we Europeans can use it, but I can't find how to change the format of the numbers on the axes.

I did find out that [this line](https://github.com/Quartz/Chartbuilder/blob/master/js/gneisschart.js#L706) takes care of formatting numbers on horizontal bar charts but can't figure out the rest.

Any clue?

Thanks for the great tool!

**Comment by yanofsky** [comment]
Hey @n-kb to change the way the numbers show up on the axes you'll need to add a number formatter (using `tickFormat` https://github.com/mbostock/d3/wiki/SVG-Axes#tickFormat) to the yAxis here https://github.com/Quartz/Chartbuilder/blob/master/js/gneisschart.js#L966

Similarly you might want to change this line https://github.com/Quartz/Chartbuilder/blob/master/js/gneisschart.js#L19 to deal with date formatting

**Comment by n-kb** [comment]
Thanks so much!

**Comment by fdaudens** [comment]
Hi @yanofsky, I'm trying to do the same thing with the v2. Do you have any idea where it's located?

**Comment by yanofsky** [comment]
@fdaudens here https://github.com/Quartz/Chartbuilder/blob/master/src/js/components/chart-xy/XYRenderer.jsx#L859-L869

which references here: https://github.com/Quartz/Chartbuilder/blob/e1954d4e4a66a256c682ac0929fe5eae79da6462/src/js/util/helper.js#L111-L139

Happy to take a pull req that deals with localizations more cleanly!

**Comment by fdaudens** [comment]
Thanks you so much! It would be a pleasure to contribute, I will try to see if I'm able to write something cleaner.
