### ISSUE TITLE
Setting Series Type to "column" in chartbuilder.php caused js error

### ISSUE THREAD

**Issue by guywhelan** [Quartz/Chartbuilder#139]
I would like the default chart to show up with a "column" chart type. I can change the type to "scatter" or "line" and it works. If I change it to "column" I get the js error:
895 TypeError: 'undefined' is not an object (evaluating 'd3.selectAll("#rightAxis.yAxis g:not(.topAxisItem) text")[0].pop().getBoundingClientRect')
If I change it to "bargraph" I get the js error:
1997TypeError: 'undefined' is not an object (evaluating 'seriesByType[series[i].type].push')
I can use "line" or "scatter" without incurring any such errors.
Thanks for all you do.

**Comment by yanofsky** [comment]
hi @guywhelan ,

could you provide the data you're using?

**Comment by guywhelan** [comment]
Thanks for such a quick response.
So far I have the standard install with only 1 change.
The only thing I changed was in gneisschart.js on line 81 I changed it from <strong>type: "line",</strong> to <strong>type: "column",</strong> You can see the results at http://www.guywhelan.com

My goal is to make the chart dynamic, displaying data from my database upon loading. I would like it to default to a column chart instead of a line chart.

**Comment by yanofsky** [comment]
@guywhelan 

I think the issue is that you took out the default data. Chartbuilder (as you can see) fails when there is no data on load

We should be releasing Chartbuilder 2.0 in the next week or two, which will have many major improvements one of which is a solution to this problem

**Comment by guywhelan** [comment]
Glad to hear that! I'd be glad to help test if needed.

**Comment by guywhelan** [comment]
Just curious how Chartbuilder 2.0 is coming along.

**Comment by yanofsky** [comment]
we're writing up documentation and turtorials at the moment, so...soon
