### ISSUE TITLE
Chartbuilder 2.0: Alt fonts render on screen but don't work on download

### ISSUE THREAD

**Issue by jgriffiths88** [Quartz/Chartbuilder#163]
To reproduce:
Go to http://data.scmp.io:8888/ 
Download image
Fonts are not those that appear on screen 

We changed the fonts used to our house style but though they appear on the screen fine, when you go to download, the system renders the image with a default font (either Arial or Times New Roman).

**Comment by yanofsky** [comment]
Hey @jgriffiths88 would it be possible to share your fork so I can take a look?

At first glance I suspect that is a result of trying to use local font files i.e. `local('Amplitude Light'), local('Amplitude-Light')` 

Does the problem persist you remove the `local()` definitions?

**Comment by jgriffiths88** [comment]
Thanks! 

https://github.com/jgriffiths88/Chartbuilder-SCMP/tree/scmp

The main version uses local font files with no problem though right? Have set it to just definite urls for the fonts but this didn't work previously (unable to test now as at home, can't push to server, seems to work on local).

**Comment by yanofsky** [comment]
Cool.

You should be able to put fonts in `/src/fonts/` and reference them as `url('/fonts/your-font.woff')`

Report back how it works in production!

**Comment by nsonnad** [comment]
Hey @jgriffiths88, looks like we were missing some info on the logistics of the build process, I added a quick thing on that [at docs/deploying.md](https://github.com/Quartz/Chartbuilder/blob/master/docs/deploying.md). Possible that this is related to your issue

**Comment by jgriffiths88** [comment]
Thanks both!

**Comment by cedricsam** [comment]
Yesss! It works! Thank you @yanofsky @nsonnad.

**Comment by jgriffiths88** [comment]
http://data.scmp.io/chartbuilder/ Thanks again guys!

**Comment by petulla** [comment]
@yanofsky / @nsonnad 

I'm having the same issue. Any chance you could take a quick look? 

http://dataviz.tools.msnbc.com/

Used npm build and hosted fonts. Not appearing on download..

**Comment by wfreitasnexo** [comment]
!o!

**Comment by yanofsky** [comment]
@petulla the two things I've seen that screw with the fonts are caused by cross domain requests and defining or applying them too high in the cascade e.g. defining `font-family` on `body` instead of `.axis`.

**Comment by edmundtadros** [comment]
I had the same problem. Solved it by calling the font with "//...link" instead of https or http.

**Comment by petulla** [comment]
For whatever reason, I needed to use:

`url('../../fonts/your-font.woff')`

rather than

`url('./../fonts/your-font.woff')`

even though the fonts appeared on the editable version.

**Comment by roberthuttinger** [comment]
is there a way to get a custom font to display in the image if the build folder is ported to another server?

**Comment by yanofsky** [comment]
@roberthuttinger I'm not sure what you're describing. could you elaborate?

**Comment by roberthuttinger** [comment]
I can get the custom font to load for the preview, but when I create an image the font doesn't display. https://imagebin.ca/v/2dAOTEnj372a but ends up looking like https://imagebin.ca/v/2dAP6Zqf8A6a when the image is generated. I was able to do this with google charts by adding an inline style and preloading the font inline, the process is a little different here though.

**Comment by roberthuttinger** [comment]
Base64 encoding is what makes it work.

Example:
`@font-face {
font-family: 'Towel-FourtyTwo';
src: url(data:application/x-font-truetype;charset=utf-8;base64,T1RUTwAMA...wATcBD/+w) format('truetype'),
     url('http://website.org/chartbuilder/fonts/Vitesse-Medium.ttf') format('truetype');
font-weight: normal;
font-style: normal;
}`

**Comment by nsonnad** [comment]
Hmm @roberthuttinger, that's interesting since the gulpfile is supposed to automatically embed fonts as base64, see [here](https://github.com/Quartz/Chartbuilder/blob/master/gulpfile.js#L34-L37). Are your fonts being defined in a stylus file in `./src` or somewhere else? Or maybe the base 64 conversion is having trouble with the `truetype` format? FYI the conversion is handled by [gulp-css-base64](https://github.com/zckrs/gulp-css-base64)

**Comment by roberthuttinger** [comment]
Aha! I was attempting to modify the build files as I mentioned earlier, I will try to rebuild later and make sure it worked as it should have. Its my own ignorance (new to node platform). 
This is great! thanks!
