### ISSUE TITLE
Commas in data break Chartbuilder sometimes

### ISSUE THREAD

**Issue by yanofsky** [Quartz/Chartbuilder#169]
year|foo
----|----
1989|$6,530
1992|$8,711
1995|$7,907
1998|$9,507
2001|$9,293
2004|$13,865
2007|$15,779
2010|$9,360
2013|$8,000

will cause Chartbuilder to crash but

year|foo
----|----
1989|$6530
1992|$8711
1995|$7907
1998|$9507
2001|$9293
2004|$13865
2007|$15779
2010|$9360
2013|$8000

wont

**Comment by nsonnad** [comment]
Fixed. Issue was that the regex that was stripping out non-number chars didn't have a global flag, so it was only getting rid of one character. I added a comma+$ case as well to the parser tests.
