### ISSUE TITLE
Save current settings to LocalStorage?

### ISSUE THREAD

**Issue by mhkeller** [Quartz/Chartbuilder#170]
What do you think of storing the chart settings in LocalStorage to protect against refreshing / closing the browser inadvertently and losing the project? To protect against always being confronted by your last chart, you could have a "Load previous" button.

**Comment by nsonnad** [comment]
This is already implemented. There is a localStorage timer that starts on page load, and the "Load previous" button persists for some time (currently 30sec), after which it starts saving the current chart to localStorage on change.

Here's the component that controls that button:
https://github.com/Quartz/Chartbuilder/blob/master/src/js/components/LocalStorageTimer.jsx

The timer is controlled via the Session flux store:
https://github.com/Quartz/Chartbuilder/blob/master/src/js/stores/SessionStore.js

**Comment by mhkeller** [comment]
I must have changed something else then. Thanks!
