### ISSUE TITLE
Export chart settings to JSON

### ISSUE THREAD

**Issue by mhkeller** [Quartz/Chartbuilder#171]
To better handle a copy edit workflow, it would be great if we could export a json of the chart settings and the interface could read such a file. 

If someone an editor needs to modify the chart, they could load the json file to get back to the previous state and re-export as opposed to having to replicate the styling manually and potentially miss something.

**Comment by nsonnad** [comment]
Would you want to save the JSON as text files or are you thinking of doing this with some kind of backend? The entire state of the chart lives in the state of the parent [Chartbuilder component](https://github.com/Quartz/Chartbuilder/blob/master/src/js/components/Chartbuilder.jsx), you could pass an `onSave` function down to that that returns its current state (to save), and load it back in later.

For now you can access the latest chart's JSON via `localStorage.getItem('model')`, but currently there is no way to get it back in (short of `localStorage.setItem('model', BUNCH_O_JSON)`)

**Comment by mhkeller** [comment]
A text file would work for what I was envisioning. We would save that to a git repository or where ever we keep track of the original excel / data files used in the piece.

**Comment by yanofsky** [comment]
For the load back in we could do some magic drag and drop or blob copy paste

i.e. download blob via button > close chartbuilder > realize there's a typo > repoen chartbuilder > drag json file to chartbuilder > EVERYTHING LOADS LIKE MAGIC > fix your typo > download new blob

**Comment by eyeseast** [comment]
+1 on this. Would really like a way to edit someone else's charts without having to stand over their shoulder or steal their laptop.

**Comment by yanofsky** [comment]
Hey @nsonnad, I wired up the ability to download/upload JSON by clicking a new download button/dragging a JSON file to the the data input.

Can you take a look and let me know if you think this stuff should live somewhere else? https://github.com/Quartz/Chartbuilder/compare/feature-download-json

Also before we incorporate this into master we need some way to validate the blob and we need some way to pass the state from DataInput to Charbuilder...thoughts?

**Comment by nsonnad** [comment]
Refactored that a bit, added validation and passing of the state, created a PR with some more todo items: https://github.com/Quartz/Chartbuilder/pull/180

**Comment by mhkeller** [comment]
If I wanted to take a crack at writing tests for this per #180, should I follow make a new file and follow the conventions in the `test/` folder?

**Comment by nsonnad** [comment]
Added the tests in https://github.com/Quartz/Chartbuilder/commit/6026161af5acec173b68dd07b4599832db0277a5. That PR should be ready to merge but would like to take another quick look when I get a chance. @mhkeller @yanofsky look good?

**Comment by mhkeller** [comment]
Looks pretty good — data appears to be loading properly. I'm loading it by drag and dropping the json over the "input your data" box. Is that the only way? Where to drag it could use a label or a specific "load chart json" button.

I could see folks getting confused if "Load previous chart" button is also visible and they click on that thinking it will open a file picker to select their json file. Should "Load chart data" be its own section with options for "Load previous chart" (if it exists in local storage) and "Load from file"?

**Comment by yanofsky** [comment]
I just added some text that says "if you have a json file to load, drop that here" and some style changes to match, bumped the minor version number and merged.

I think that solves the "Load previous chart" confusion, but we could also change that to "Load last chart"

**Comment by yanofsky** [comment]
@mhkeller feel free to leave any more thoughts you have here, and we can incorporate them in a patch

**Comment by mhkeller** [comment]
Thanks

**Comment by mhkeller** [comment]
Could you publish 2.1.0 to npm?

**Comment by yanofsky** [comment]
@nsonnad, can you handle?

**Comment by nsonnad** [comment]
Done.
