### ISSUE TITLE
Tmp directory in Gulp file

### ISSUE THREAD

**Issue by petulla** [Quartz/Chartbuilder#190]
@nsonnad, what is the `tmp` path/directory supposed to be utilized for?  I don't see any gulp streams to it , but it is setup in config and in the `clean` task. Can the object key be deleted from config?

**Comment by nsonnad** [comment]
Hey @petulla, good catch and thanks for pointing out. It looks like this is cruft from when we were using a preprocessor to strip out conditional code blocks for prod/dev environments. We are now using [envify](https://github.com/hughsk/envify) which is smarter and doesn't require a temporary staging directory, previously we had to preprocess the files then put them somewhere for browserify/stylus/etc to look.

Short answer: yes it can be deleted

**Comment by petulla** [comment]
Cool, going to PR.
