### ISSUE TITLE
SecurityError on image download in latest FireFox

### ISSUE THREAD

**Issue by mhkeller** [Quartz/Chartbuilder#192]
I'm getting `SecurityError: The operation is insecure.` when i try and download the chart image in FireFox 41.0.1. This is true in both the latest version when I host it locally and in the hosted version at http://quartz.github.io/Chartbuilder/build/

![chartbuilder](https://cloud.githubusercontent.com/assets/498744/10492723/8dacd8c2-727b-11e5-98da-baff32ec7908.gif)

**Comment by yanofsky** [comment]
hmmm, is it possible you have a plugin that would interfere or manipulate the SVG > Canvas > Image flow? I just tried on FF 41.0.1 and couldn't replicate

**Comment by mhkeller** [comment]
Hmm so I had turned off Privacy Badger but even in a deactivated state, it seems to be the culprit, which is super weird. Good to know for the future
