### ISSUE TITLE
How do I edit the space in the ticks at the bottom?

### ISSUE THREAD

**Issue by edmundtadros** [Quartz/Chartbuilder#193]
Where would I look to find the settings for this bit of the graph? I'd like to edit the space between the tick and horizontal line and number/value.

![screenshot_1](https://cloud.githubusercontent.com/assets/7545454/10562060/e685d5dc-7593-11e5-9d4f-0e0d33c9a63c.png)

**Comment by yanofsky** [comment]
Sorry for the slow reply!

I think you're looking for this 
https://github.com/Quartz/Chartbuilder/blob/master/src/js/charts/cb-xy/draw-xy.js#L21

**Comment by edmundtadros** [comment]
Thanks. Perfect.
