### ISSUE TITLE
npm dev run doesn't work

### ISSUE THREAD

**Issue by edmundtadros** [Quartz/Chartbuilder#199]
Hi,
Not sure what is happening here. I was updating my repo and went to run it and got an error. So I updated my packages but still get this error when I do npm dev run. Have I missed anything?

npm-DEBUG.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.5.2
3 info using node@v4.1.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle chartbuilder@2.2.0~predev: chartbuilder@2.2.0
6 silly lifecycle chartbuilder@2.2.0~predev: no script for predev, continuing
7 info lifecycle chartbuilder@2.2.0~dev: chartbuilder@2.2.0
8 verbose lifecycle chartbuilder@2.2.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle chartbuilder@2.2.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/et/Documents/tools/chartbuilder/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle chartbuilder@2.2.0~dev: CWD: /Users/et/Documents/tools/chartbuilder
11 silly lifecycle chartbuilder@2.2.0~dev: Args: [ '-c', 'gulp' ]
12 silly lifecycle chartbuilder@2.2.0~dev: Returned: code: 1  signal: null
13 info lifecycle chartbuilder@2.2.0~dev: Failed to exec dev script
14 verbose stack Error: chartbuilder@2.2.0 dev: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:817:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid chartbuilder@2.2.0
16 verbose cwd /Users/et/Documents/tools/chartbuilder
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v4.1.1
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error chartbuilder@2.2.0 dev: `gulp`
22 error Exit status 1
23 error Failed at the chartbuilder@2.2.0 dev script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the chartbuilder package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs chartbuilder
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls chartbuilder
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

TERMINAL FEEDBACK:
[10:44:57] Finished 'copy-htdocs' after 1.05 s
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: module "react/lib/shallowEqual" not found from "/Users/et/Documents/tools/chartbuilder/src/js/components/svg/ChartFooter.jsx"
    at notFound (/Users/et/Documents/tools/chartbuilder/node_modules/browserify/index.js:803:15)
    at /Users/et/Documents/tools/chartbuilder/node_modules/browserify/index.js:754:23
    at /Users/et/Documents/tools/chartbuilder/node_modules/browser-resolve/index.js:185:24
    at /Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:44:14
    at process (/Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:113:43)
    at /Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:122:21
    at load (/Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:54:43)
    at /Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:60:22
    at /Users/et/Documents/tools/chartbuilder/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! chartbuilder@2.2.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chartbuilder@2.2.0 dev script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chartbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chartbuilder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chartbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/et/Documents/tools/chartbuilder/npm-debug.log

**Comment by yanofsky** [comment]
Looks like you had a bad merge.
```
Error: module "react/lib/shallowEqual" not found from "/Users/et/Documents/tools/chartbuilder/src/js/components/svg/ChartFooter.jsx"
```
means that `var shallowEqual = require("react/lib/shallowEqual");` is still in `ChartFooter.jsx` however that should have been removed in the upgrade.

**Comment by edmundtadros** [comment]
Thanks. I remerged and that fixed it.
