### ISSUE TITLE
Is there a way to wrap tspan

### ISSUE THREAD

**Issue by roberthuttinger** [Quartz/Chartbuilder#235]
Making tspan word wrap? Currently the text falls off the edge of the planet. Still looking and experimenting...

**Comment by yanofsky** [comment]
Hi @roberthuttinger Are you talking about using the functionality on this branch or something else? https://github.com/Quartz/Chartbuilder/tree/golfecholima-subtitle

**Comment by roberthuttinger** [comment]
created a second subtitle that allows a second line of text. It looks like breaking ene element into multiple tspans would require some serious shim code.

**Comment by yanofsky** [comment]
It's not _so_ hard. Take a look at this https://bl.ocks.org/mbostock/7555321
