### ISSUE TITLE
Initialize tangle axis with zero instead of 30

### ISSUE THREAD

**Issue by roberthuttinger** [Quartz/Chartbuilder#236]
Tried explicitly setting defaults to zero but it looks like there is a check to return '' on zero. Setting the default to zero allows the zero to be displayed, but the binding is done on the fly so there is no external trigger for updating.

Im sure this is a simple issue, any idea where I can set the min == 0 in main.js?

**Comment by nsonnad** [comment]
The default is based on the domain of the data (or `0` by default for column charts). It only gets set to an explicit value once it is customized. Do you just want it to be `0` on the default data or for any data that is pasted in?

**Comment by roberthuttinger** [comment]
0 default

**Comment by nsonnad** [comment]
For any data?

**Comment by roberthuttinger** [comment]
Any new data. The user could then change it, but zero should be the default

**Comment by nsonnad** [comment]
To do this, you'll want to modify the behavior of the `compute_scale_domain` helper function, [found here](https://github.com/Quartz/Chartbuilder/blob/master/src/js/util/helper.js). 

you could change this (line 75)

```
if (!scaleObj.domain || !scaleObj.custom) {
	if (opts.nice) {
		_domain = niced;
	} else {
		_domain = extent;
	}
	defaultMin = true;
	defaultMax = true;
} else {
```
to 

```if (!scaleObj.domain || !scaleObj.custom) {
	if (opts.nice) {
		_domain = [0, d3.max(niced)];
	} else {
		_domain = [0, d3.max(extent)];
	}
	defaultMin = true;
	defaultMax = true;
} else {
```

**Comment by roberthuttinger** [comment]
Awesome! I noticed that section but the syntax escaped me, and still wasnt sure after testing.

Perfect, works like a charm thanks!
