### ISSUE TITLE
Disable `date` parsing?

### ISSUE THREAD

**Issue by roberthuttinger** [Quartz/Chartbuilder#239]
Tried setting Ln.~ 43360 `supportedInputTypes.date = false` but if I paste content in, the data is still parsed as a date if the col header is `date`

Is this set somewhere else?

Thanks!

**Comment by yanofsky** [comment]
`supportedInputTypes` is not a Chartbuilder setting, it's something used by an imported module.

If you want to disable that functionality you'll have to remove this line https://github.com/Quartz/Chartbuilder/blob/e1954d4e4a66a256c682ac0929fe5eae79da6462/src/js/util/parse-utils.js#L2

**Comment by roberthuttinger** [comment]
aha! `parseDelimInput` that makes sense but you never know the syntax. Thanks for helping find that! Exactly what was needed!
