### ISSUE TITLE
Adding Dollar Sign to Prefix Causes misalignment

### ISSUE THREAD

**Issue by roberthuttinger** [Quartz/Chartbuilder#240]
When adding a dollar sign to the prefix, it causes the value to shift to the right, and apparently change from right align, to left align. Is there a way to suppress this behaviour? Using the letter `r` does not cause this to happen. It looks like ~Ln.2967 this would effect change, but it doesnt.

**Comment by yanofsky** [comment]
I'm not seeing that happen here http://quartz.github.io/Chartbuilder/ are you sure this isn't the result of a customization?

**Comment by roberthuttinger** [comment]
Too right! I apologize for not checking the root first!
