### ISSUE TITLE
Deploy to S3?

### ISSUE THREAD

**Issue by bradoyler** [Quartz/Chartbuilder#246]
I'd like to add a new deploy option for upload/sync of assets to an AWS S3 bucket. 📦  
Would likely use the gulp plugin [awspublish](https://github.com/pgherveou/gulp-awspublish)

Using [AWS MFA](https://aws.amazon.com/iam/details/mfa/) is also a requirement for me, but I can add that in later, via my [aws-MFA](https://github.com/bradoyler/aws-mfa) package that is under development.

**Comment by yanofsky** [comment]
This is to deploy the compiled app, not to upload created charts, right? 

If that's the case, I'm not opposed.

**Comment by bradoyler** [comment]
@yanofsky Correct. Thanks.
