### ISSUE TITLE
Improve BrowserSync times

### ISSUE THREAD

**Issue by bradoyler** [Quartz/Chartbuilder#248]
Hey Chartbuilders... 
whenever I update js file, I am seeing very slow (~4s) reload times. 
![screen shot 2016-07-07 at 1 53 54 pm](https://cloud.githubusercontent.com/assets/425966/16663567/7db4f35e-444a-11e6-974f-b58efcee511a.png)

This could be fixed by using watchify, like so: https://gist.github.com/wesbos/52b8fe7e972356e85b43

@nsonnad Lmk if you're open to this change and I'll start a PR. 🚀

**Comment by nsonnad** [comment]
Thanks @bradoyler, I had actually opened an issue for this a while back, #165. Would be happy to look at a PR!

**Comment by nsonnad** [comment]
Closed as dupe with #165
