### ISSUE TITLE
Line weight not reflected in exports

### ISSUE THREAD

**Issue by duner** [Quartz/Chartbuilder#260]
Given this chart in the preview in the GUI:

![screen shot 2017-02-09 at 5 57 50 pm](https://cloud.githubusercontent.com/assets/2475973/22806701/4f084cca-eef1-11e6-8843-465c962842d3.png)

When exporting, the line weight doesn't appear to get carried over.

![juice_travel_chartbuilder 71](https://cloud.githubusercontent.com/assets/2475973/22806712/649204a0-eef1-11e6-8e2b-96f3baebb1d9.png)

This is in Chartbuilder 3.0.

**Comment by nsonnad** [comment]
I believe I fixed this in #262, does it work for you guys?

**Comment by petulla** [comment]
This did work yes. It also corrects the application of styles overall.

**Comment by nsonnad** [comment]
Thanks, merged
