### ISSUE TITLE
Error: Cannot find module 'reactify'

### ISSUE THREAD

**Issue by khantasha** [Quartz/Chartbuilder#261]
Hi. I've tried downloading chartbuilder locally a few times and I keep coming up with this same error. 
![screen shot 2017-02-15 at 12 24 05 pm](https://cloud.githubusercontent.com/assets/5297401/22986477/aa916248-f379-11e6-90a5-43284dba3beb.png)

**Comment by khantasha** [comment]
I've done:

npm install reactify
npm intall reactify

and it still doesn't work

**Comment by nsonnad** [comment]
This was an issue with chartbuilder-ui after switching the chartbuilder build process to `babelify`. Can you try pulling the latest chartbuilder, version 3.0.3, and doing `npm install` in a fresh directory?

**Comment by khantasha** [comment]
I just cloned this repo https://github.com/Quartz/Chartbuilder
This isn't the most current version? If not, where can I pull it from? thanks for your help.

**Comment by nsonnad** [comment]
Sorry, I just mean please try doing it again, as I have made some changes that should fix your issue

**Comment by khantasha** [comment]
That worked like a charm! Thank you!
