### ISSUE TITLE
export as true grays for print

### ISSUE THREAD

**Issue by shmcminn** [Quartz/Chartbuilder#272]
Request/question if this is possible - is there a way to set the "gray" colors so that when they export they have a color scheme like:

C:0 
M:0 
Y:0 
K: {XX%} 

For those of us who use these in newsprint, this prevents problems when the color printer tries to print gray additively and the alignment is *slightly* off.

**Comment by yanofsky** [comment]
Hey Sean, are you talking about the SVG or the PNG export?

**Comment by shmcminn** [comment]
We would use this in the SVG export

**Comment by yanofsky** [comment]
Depending on your production workflow, the solution might just be to add [cmyk specs](https://www.w3.org/TR/css-color-4/#cmyk-colors) to the stylesheet. SVG supports cmyk with version 2.0.

Unfortunately if you're using Adobe Illustrator you're going to be out of luck. Illustrator opens and saves SVG in RGB seemingly always and ignores the cmyk based css.

You might be best off scripting a solution inside of whatever software you're using in production.
