### ISSUE TITLE
Audience

### ISSUE THREAD

**Issue by zzolo** [Quartz/Chartbuilder#41]
My initial impression of ChartBuilder was that it is a deployable application for news organizations (or whoever) that can be customized so that reporters (or other non-technical folks) can easily create charts with design attributes that are consistent with the organization.

Specifically, this means that the actual code and deployment is aimed at developers or system administrators at a news organizations, while the end user of the deployed application are reports/non-technicals.

If this is the case, I would propose changing around a few things and ensuring that the right audience is addressed.

The README should be focused on:

* Short description of what the deployed application does -- make great charts.
* How to install and deploy.  This is actually pretty simple, and with Github pages, you don't even need your own server.
* How to customize the application for your organization and design needs.  This should describe all the configuration options and how to fill in the design specs, and possibly take away interface choices.
* How to contribute and any other developer focused information.

On the flip side, there should be some generic inline help in the application itself that describes how to make a chart, aimed speaking to the people actually using the deployed application.  Right now, this exists in the README where it is separated from the deployed application and it is not a place an end-user (reporter) would go to.

Let me know if this makes sense, and I can start maybe working on a pull request.

**Comment by yanofsky** [comment]
I think we covered this all with v2!
